# docker-compose versão 2
version: '2'

# Serviços
services:

  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
      - logs-web:/var/log/nginx
      - /var/www/html:/var/www/html
    links:
      - php:php
    restart: always
    network_mode: bridge

  # php-fpm
  php:
    build: .
    expose:
      - "9000"
    volumes:
      - /var/www/html:/var/www/html
      - logs-php-fpm:/var/log/php-fpm
    links:
      - postgres:postgres
    restart: always
    network_mode: bridge

# postgres
  postgres:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    network_mode: bridge

# Volumes
volumes:
  logs-php-fpm:
    driver: local
  logs-web:
    driver: local
  pg-data:
    driver: local
