# docker-compose versão 2
version: '2'

# Serviços
services:

  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
      - logs-web:/var/log/nginx
      - app-sync:/var/www/html:cached
    links:
      - php:php
    restart: always
    network_mode: bridge

  # php-fpm
  php:
    build: .
    expose:
      - "9000"
    volumes:
      - app-sync:/var/www/html:cached
      - logs-php-fpm:/var/log/php-fpm
    links:
      - postgres:postgres
    restart: always
    network_mode: bridge

# postgres
  postgres:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    network_mode: bridge

#pgadmin4
  #pgadmin:
  #  image: fenglc/pgadmin4
  #  ports: 
  #    - "5050:5050"
  #  environment:
  #    DEFAULT_PASSWORD: 123
  #    DEFAULT_USER: admin
  #  links:
  #    - postgres:postgres
  #  restart: always
  #  network_mode: bridge

# gearman
  gearman:
    image: kendu/gearman
    ports:
      - "4730:4730"
    restart: always
    network_mode: bridge

# Volumes
volumes:
  logs-php-fpm:
    driver: local
  logs-web:
    driver: local
  pg-data:
    driver: local
  app-sync:
    external: true
