# docker-compose versão 2
version: '2'

# Serviços
services:

  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
      - logs-web:/var/log/nginx
      - app-sync:/var/www/html
    links:
      - php:php
    restart: always
    network_mode: bridge

  # php-fpm
  php:
    build: .
    expose:
      - "9000"
    volumes:
      - app-sync:/var/www/html
      - logs-php-fpm:/var/log/php-fpm
    links:
      - postgres:postgres
      - gearman:gearman
    restart: always
    network_mode: bridge

# postgres
  postgres:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    network_mode: bridge

# gearman
  gearman:
    image: kendu/gearman
    ports:
      - "4730:4730"
    restart: always
    network_mode: bridge

# supervisord
  supervisord:
    image: eduardorfreitas93/alpine-supervisord-docker
    volumes:
      - ./conf/supervisord/conf:/etc/supervisor/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/supervisord/logs:/var/log
    restart: always
    network_mode: bridge

# ELK
  # elk:
  #   image: willdurand/elk
  #   ports:
  #       - "81:80"
  #   volumes:
  #       - ./conf/elk/logstash:/etc/logstash
  #       - ./conf/elk/logstash/patterns:/opt/logstash/patterns
  #       - logs-php-fpm:/tmp/var/logs
  #   network_mode: bridge
  #   volumes_from:
  #     - php

#pgadmin4
  #pgadmin:
  #  image: fenglc/pgadmin4
  #  ports: 
  #    - "5050:5050"
  #  environment:
  #    DEFAULT_PASSWORD: 123
  #    DEFAULT_USER: admin
  #  links:
  #    - postgres:postgres
  #  restart: always
  #  network_mode: bridge

# gearman
  # gearman:
  #   image: kendu/gearman
  #   ports:
  #     - "4730:4730"
  #   restart: always
  #   network_mode: bridge

# Volumes
volumes:
  logs-php-fpm:
    driver: local
  logs-web:
    driver: local
  pg-data:
    driver: local
  app-sync:
    external: true
